# Generated by Django 2.1.2 on 2018-10-31 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('tasks_management', '0001_initial'), ('tasks_management', '0002_auto_20181031_1440'), ('tasks_management', '0003_auto_20181031_1445'), ('tasks_management', '0004_auto_20181031_1453'), ('tasks_management', '0005_auto_20181031_1532')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to='tasks_management.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='tasks_management.User'),
        ),
    ]
